version: '3'
#コンテナ
services:
  #コンテナ1
  python:
      container_name: django_docker
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      working_dir: /app
      ports:
        - 8000:8000
      volumes:
        - .:/app
      depends_on:
        - mysql
  #コンテナ2
  mysql:
      container_name: mysql
      #M1
      platform: linux/x86_64 
      image: mysql:8.0
      restart: always
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
      environment:
        MYSQL_DATABASE: mysql
        MYSQL_USER: django
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
        TZ: 'Asia/Tokyo'
      ports:
        - "3306:3306"
      volumes:
        - ./mysql:/var/lib/mysql
