version: '3'
#コンテナ
services:
  #コンテナ1
  python:
      container_name: django_docker
      #M1
      platform: linux/amd64
      build: .
      working_dir: /app/board_django
      ports:
        - 8000:8000
      volumes:
        - .:/app
      depends_on:
        - mariadb
      expose:
        - '8000'
  #コンテナ2
  mariadb:
      container_name: mariadb
      image: mariadb:10.4
      restart: always
      environment:
        MYSQL_DATABASE: django
        MYSQL_USER: django
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
        TZ: 'Asia/Tokyo'
      ports:
        - "3306:3306"
      volumes:
        - ./mariadb:/var/lib/mysql
